### PR TITLE
fix: catch error when all promises reject

### LINKED ISSUE #148: AggregateError: aggregate error
Sentry Issue: [PINEAPPLE-4](https://snapshot-labs.sentry.io/issues/4360534004/?referrer=github_integration)

```
AggregateError: aggregate error
  File "/workspace/node_modules/bluebird/js/release/some.js", line 82, in SomePromiseArray._checkOutcome
    var e = new AggregateError();
  File "/workspace/node_modules/bluebird/js/release/some.js", line 69, in SomePromiseArray._promiseRejected
    return this._checkOutcome();
  File "/workspace/node_modules/bluebird/js/release/promise.js", line 611, in Promise._settlePromise
    receiver._promiseRejected(value, promise);
  File "/workspace/node_modules/bluebird/js/release/promise.js", line 649, in Promise._settlePromise0
    this._settlePromise(promise, handler, receiver, value);
  File "/workspace/node_modules/bluebird/js/release/promise.js", line 725, in Promise._settlePromises
    this._settlePromise0(this._rejectionHandler0, reason, bitField);
...
(7 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by wa0x6e**
## 🧿 Current issues / What's wrong ?

`Promises.any` is not catch, and will throw an `AggregateError` when all promises reject

## 💊 Fixes / Solution

Handle the `AggregateError`

Fixes #148 
Fixes PINEAPPLE-4

## 🚧 Changes

- Catch the `AggregateError` and return a 400 error code. Will assume that if all gateways fail, the input is probably not valid
- __Add a timeout when requesting gateways__: This will resolve the high memory consumption
- try/catch the AWS set logic
- Use `node-fetch` directly instead of `cross-fetch`
- Remove `bluebird`, and use directly built-in Promise from js

## 🛠️ Tests

- Go to `http://localhost:3000/ipfs/QmS8JB9s69bWLR7GQHQU6D15jV3LuvAuSStC6b1UwyYSk8`
- It should print something
- Go to `http://localhost:3000/ipfs/test`
- It should return a 400 error

### CODE REVIEW

File: src/proxy.ts [hunk 1]
```diff
@@ -13,15 +13,32 @@ router.get('/ipfs/*', async (req, res) => {
...
+
+          if (!response.ok) {
+            return Promise.reject(response.status);
+          }
+          return response.json();
+        })
+      );
+      res.json(json);
+    } catch (e: any) {
+      return res.status(400).json();
```
Comment (Todmy) [inline src/proxy.ts:33]:
```suggestion
      capture(e);
      return res.status(400).json();
```

File: src/proxy.ts [hunk 2]
```diff
@@ -13,15 +13,32 @@ router.get('/ipfs/*', async (req, res) => {
...
+    }
+
+    try {
+      const size = Buffer.from(JSON.stringify(json)).length;
+      if (size <= MAX) await set(`cache/${key}`, json);
+    } catch (e: any) {
+      capture(e);
```
Comment (Todmy) [inline src/proxy.ts:40]: In this particular case, we need to throw an error again that we need to get to the outer catch
```suggestion
      capture(e);
      throw e
```

File: src/proxy.ts [hunk 3]
```diff
@@ -13,15 +13,32 @@ router.get('/ipfs/*', async (req, res) => {
...
-        return fetch(url).then(res => res.json());
-      })
-    );
-    res.json(json);
-    const size = Buffer.from(JSON.stringify(json)).length;
-    if (size <= MAX) await set(`cache/${key}`, json);
+
+    let json;
+
+    try {
```
Comment (Todmy) [inline src/proxy.ts:19]: why do we need this nested try-catch? then the one on line 13 doesn't make sense

File: src/proxy.ts (hunk 1 above)
Comment (wa0x6e) [reply src/proxy.ts:33]: I will avoid catching 400 errors. The try/catch should catch only AggregateError, which is thrown only when all the gateways fail. Only reason all fails is that the IPFS hash does not exist.

File: src/proxy.ts (hunk 2 above)
Comment (wa0x6e) [reply src/proxy.ts:40]: Try/catch is there to let the AWS `set` function fail silently, such as when credentials are missing.

File: src/proxy.ts (hunk 3 above)
Comment (wa0x6e) [reply src/proxy.ts]: fixed, it was used because `Promise.any` was not throwing the correct error. It was because it was using Promise from the bluebid package, instead of built-in one

**Review by Todmy — APPROVED** [review]
utACK
